env:
  global:
    - secure: "svC6w9V3t7kifmOX1Fx4ahhtKr+PB13WsMPQ4uR0z9ACxl4ZT3av0OmVrGhDYkIjwcHAb1D7t7RpfrmMRF9frO6CSG7JJof5Rfy0Kcqaz/xrYnGF8AiSwlzGmya9bG95QiP66WA9lXIQqzHQM05dI7FktDK1XWNWeaJmc8QryABJFdR4TFxIXZardQdrbsRQ0Z8WUlQD80pgyj0Hvbz7zjzEnTLsmtFmrx3wviaDda1XFvRP2pwBK08zn9rxwojihRC+/5euLTgewrart44WCqzQwb9cghOTNJ6Q+dJ4UyvdIiSY0Chmrs/Y9o9WZGnkl3iEI6LdZC3b4XrVeAytE74LQsbALJEwGUxy1ikhCOFEHHoDV1Rz3kXqmYKKl3o+dWSwv4iBtWhxA8YQST2j43QYb6Rp2OEv0mR10Pu1TXOQUqgt+NfX1csENyO6idUtzn4nb4x9Zf2n5o2cyywYhXlIaJ+PEFVe7QjMe6FMCXu4uJcn4tcMtfE1dwO3bvpEcdE2A2OYbamrj9bIe3Iq00lRh8PMUJhR+zX4yRG+Pcu2Yz8CwBOduPNzZRmhE+GOQt3Y5a9msYbw5xQG7i6O3b05GNCUG2sRssbT4iruXKIHkrJOX8UkQvrNsQemqv0vO/LqIwVmR70xIGoUeN37GyPP0y9V4OPzqVRVYMRTEdw="
    - GIT_DEPLOY_DIR=public             # default output dir of Hugo (change it, when you use configured it!)
    - GIT_DEPLOY_BRANCH=master          # target branch, replace by "gh-pages" for Github Project Pages
    - GIT_DEPLOY_USERNAME="Travis CI"   # dummy name
    - GIT_DEPLOY_EMAIL=sadat.hossain@hotmail.com # replace by your email

branches:
  only:
    - sources                           # for Github Project Pages replace with "master"

install:
  - rm -rf public || exit 0             # cleanup previous run
script:
  - binaries/hugo                       # Generate
after_success:
  - cp .travis.yml public               # all branches need this file
  - bash deploy.sh                      # run the deploy
