baseURL = "/cloud3.github.io/"
languageCode = "en-us"
title = "SadatRocks"
theme = "kube"
description = "SadatRocks is the official web address of Sadat Hossain(in2sadt)"
Paginate = 10
[Params]
  RSSLink = "/index.xml"
  author = "Cloud3" # add your company name
  github = "Sadathossain" # add your github profile name
  twitter = "in2sadt" # add your twitter profile
  email = "sadat.hossain@hotmail.com"
[params.seo.webmaster_verifications]
  google = "UA-33535265-6" # Optional, Google verification code
  bing = "C44E72A3112D10E72976633D1ECE9070" # Optional, Bing verification code
  yandex = "3d45d40b94a66eb3" # Optional, Yandex verification code
[[menu.main]]
    name = "Cookbooks"
    weight = -100
    url = "/cookbooks/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
